name: logback_for_flutter
description: Logback android for flutter
version: 0.0.1
homepage: https://github.com/srikrishnacj/logback_for_flutter.git
repository: https://github.com/srikrishnacj/logback_for_flutter.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.cjcj.logback_for_flutter
        pluginClass: LogbackForFlutterPlugin
      ios:
        pluginClass: LogbackForFlutterPlugin